#!/bin/sh

#DEV=./dev
DEV=.
MACROS=LoadPrices.py

MASTER=$DEV/Templates/empty.ods
TARGET=test.ods
BUILD=t

[ ! -d $DEV ] \
    && echo "$DEV missing - not in top-level directory" 1>&2 \
    && exit 1

#fresh zipfile
rm -fr $BUILD
unzip  $MASTER -d $BUILD

#manifest
rm -fr   $BUILD/META-INF/*
cp -fp   $DEV/manifest.xml $BUILD/META-INF

#code
rm -fr   $BUILD/Scripts/python
mkdir -p $BUILD/Scripts/python
cp -fpr  $DEV/$MACROS $DEV/pythonpath $BUILD/Scripts/python

rm -f $TARGET

(cd $BUILD; $HOME/pub/bin/rpurge; zip -r ../$TARGET .)

ls -lt $TARGET*
